networks: 
  default:
    driver: bridge
    name: roboshop
    #external: true
  volumes:
    mongodb:
    mysql:
    rabbitmq:
    redis:
services:
  mongodb:
    image: anjuma11/mongodb:v1
    container_name: mongodb
    volumes:
    - mongodb:/data/db
  redis:
    image: redis:7
    container_name: redis
    volumes:
    - redis:/data
  mysql:
    image: anjuma11/mysql:v1
    container_name: mysql
    volumes:
    - mysql:/var/lib/mysql
  catalogue:
    image: anjuma11/catalogue:v1
    container_name: catalogue
    depends_on:
    - mongodb
  cart:
    image: anjuma11/cart:v1
    container_name: cart
    depends_on:
    - catalogue
    - redis
  user:
    image: anjuma11/user:v1
    container_name: user
    depends_on:
    - redis
    - mongodb
  shipping:
    image: anjuma11/shipping:v1
    container_name: shipping
    depends_on:
    - mysql
    - cart
  rabbitmq:
    image: rabbitmq:3
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: roboshop
      RABBITMQ_DEFAULT_PASS: roboshop123
    volumes:
    - rabbitmq:/var/lib/rabbitmq
  payment:
    image: anjuma11/payment:v1
    container_name: payment
    environment:
      CART_HOST: cart
      CART_PORT: 8080
      USER_HOST: user
      USER_PORT: 8080
      AMQP_HOST: rabbitmq
      AMQP_USER: roboshop
      AMQP_PASS: roboshop123
    depends_on:
    - cart
    - rabbitmq
    - user
  frontend:
    image: anjuma11/frontend:v1
    container_name: frontend
    ports:
    - "80:80"
    depends_on:
    - catalogue
    - cart
    - user
    - payment
    - shipping